project:
  type: website
  resources:
    - "tools/*/**"
    - "site_libs/**"

website:
  title: "Problem of Points"
  navbar:
    right:
      - about.qmd
      - disclaimer.qmd
      - text: Posts
        href: posts/
      - text: Tools
        href: tools/
      - icon: github
        href: https://github.com/problemofpoints
    background: "#F2F2F2"
    logo: favicons-black-letter-P.ico
  favicon: favicons-black-letter-P.ico
  page-footer: 
    center:
      - text: "Copyright Â© 2025 problemofpoints"
format:
  html:
    theme: litera
    css: styles.css
    sourcemap: false

editor: source

execute:
  freeze: auto
  
