[project]
name = "problemofpoints"
version = "0.1.0"
dependencies = [
  "arviz>=0.22",
  "bambi>=0.16",
  "chainladder>=0.8",
  "formulae>=0.5",
  "pymc>=5.26",
  "reservetestr @ git+https://github.com/problemofpoints/reservetestr-python.git"
]
